version: "3.8"
services:
  db:
    image: mysql
    restart: always
    container_name: 'db_container'
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - /data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_container
    ports:
      - 5000:5000
    expose:
      - 5000
    command: sh -c "sleep 10s ; python3 ./app.py"
    depends_on:
      - db

volumes:
  data:
